load('inliers_results.mat', 'inliers_counts', 'threshold_range', 'iteration_counts');
%show inlier_count changes over threshold variation
figure(21), xlabel('threshold'), ylabel('inlier count'), hold on
plot(threshold_range', inliers_counts(:,1), '--rs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',10);
plot(threshold_range', inliers_counts(:,2),  '--bs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','b',...
                'MarkerSize',10);
plot(threshold_range', inliers_counts(:,3),  '--ys','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','y',...
                'MarkerSize',10);
plot(threshold_range', inliers_counts(:,4),  '--gs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','g',...
                'MarkerSize',10);
legend('8p', '8pAdapt', '8pAdaptSampson', '5p');
hold off;
saveas(21,strcat('result_images\threshold_variation.png'));
figure(22), xlabel('threshold'), ylabel('iteration counts'), hold on
plot(threshold_range', iteration_counts(:,1), '--rs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',10);
plot(threshold_range', iteration_counts(:,2),  '--bs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','b',...
                'MarkerSize',10);
plot(threshold_range', iteration_counts(:,3),  '--ys','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','y',...
                'MarkerSize',10);
plot(threshold_range', iteration_counts(:,4),  '--gs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','g',...
                'MarkerSize',10);
legend('8p', '8pAdapt', '8pAdaptSampson', '5p');
hold off;
saveas(22,strcat('result_images\thresh_iteration_counts.png'));